dataset:
  name: Lyft
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  steps_per_epoch_train: 5000

model:
  name: PointPillars
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"

  point_cloud_range: [-80, -80, -5, 80, 80, 3.0]
  classes: [
    'car', 'truck', 'bus', 'emergency_vehicle', 'other_vehicle', 'motorcycle',
    'bicycle', 'pedestrian', 'animal'
  ]

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 20
    voxel_size: &vsize
      [0.25, 0.25, 8]
    max_voxels: [60000, 60000]

  voxel_encoder:
    in_channels: 4
    feat_channels: [64]
    voxel_size: *vsize

  scatter:
    in_channels: 64
    output_shape: [640, 640]

  backbone:
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false

  head:
    in_channels: 384
    feat_channels: 384
    nms_pre: 1000
    score_thr: 0.05
    ranges: [
      [-80, -80, -1.0715024, 80, 80, -1.0715024],
      [-80, -80, -0.3033737, 80, 80, -0.3033737],
      [-80, -80, -0.3519405, 80, 80, -0.3519405],
      [-80, -80, -0.8871424, 80, 80, -0.8871424],
      [-80, -80, -0.6276341, 80, 80, -0.6276341],
      [-80, -80, -1.3220503, 80, 80, -1.3220503],
      [-80, -80, -1.0709302, 80, 80, -1.0709302],
      [-80, -80, -0.9122268, 80, 80, -0.9122268],
      [-80, -80, -1.8012227, 80, 80, -1.8012227]
    ]
    sizes: [
        [1.92, 4.75, 1.71],   # car
        [2.84, 10.24, 3.44],  # truck
        [2.92, 12.70, 3.42],  # bus
        [2.42, 6.52, 2.34],   # emergency vehicle
        [2.75, 8.17, 3.20],   # other vehicle
        [0.96, 2.35, 1.59],   # motorcycle
        [0.63, 1.76, 1.44],   # bicycle
        [0.76, 0.80, 1.76],   # pedestrian
        [0.35, 0.73, 0.50]    # animal
    ]
    rotations: [0, 1.57]
    iou_thr: [[0.3, 0.6]]
    dir_offset: 0.7854

  augment:
    PointShuffle: True
    ObjectRangeFilter:
      point_cloud_range: [-80, -80, -5, 80, 80, 3.0]


pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 6
  val_batch_size: 1
  test_batch_size: 1
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [0.7]
  difficulties: [0]
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
