dataset:
  name: WaymoSemSeg
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: []
  ignored_label_inds: [0]
  test_result_folder: ./test
  use_cache: false
model:
  name: PointTransformer
  batcher: ConcatBatcher
  ckpt_path: # path/to/your/checkpoint
  in_channels: 3
  blocks: [2, 3, 4, 6, 3]
  num_classes: 23
  voxel_size: 0.04
  max_voxels: 50000
  ignored_label_inds: [-1]
  augment: {}
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0001
  batch_size: 2
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 512
  save_ckpt_freq: 3
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 2
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
