dataset:
  name: Waymo
  dataset_path: # /export/share/Datasets/Waymo_1.3/waymo_preprocessed/  # path/to/your/dataset
  cache_dir: ./logs/cache
  # steps_per_epoch_train: 4000

model:
  name: PVRCNNPlusPlus
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"

  point_cloud_range: [-74.88, -74.88, -2, 74.88, 74.88, 4]
  classes: ['VEHICLE', 'PEDESTRIAN', 'CYCLIST']

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 5
    voxel_size: &vsize
      [0.1, 0.1, 0.15]
    max_voxels: [150000, 150000]

  voxel_encoder:
    in_channels: 4
    # feat_channels: [64]
    voxel_size: *vsize
  
  backbone_2d:
    layer_nums: [5, 5]
    layer_strides: [1, 2]
    num_filters: [128, 256]
    upsample_strides: [1, 2]
    num_upsample_filters: [256, 256]

  rpn_module:
    shared_conv_channels: 64
    num_head_conv: 2
    class_names: [ 'Vehicle', 'Pedestrian', 'Cyclist' ]
    voxel_size: *vsize
    feature_map_stride: 8
    nms_pre: 4096
    score_thr: 0.1
    post_center_limit_range: [ -75.2, -75.2, -2, 75.2, 75.2, 4 ]
    num_max_objs: 500
    gaussian_overlap: 0.1
    min_radius: 2
    cls_weight: 1.0
    loc_weight: 2.0
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  roi_grid_pool:
    rcnn_cls_weight: 1.0
    rcnn_reg_weight: 1.0
    rcnn_corner_weight: 1.0
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    code_size: 7
    num_class: 1


  voxel_set_abstraction:
    voxel_size: *vsize
    num_bev_features: 512
    num_raw_features: 5
    num_keypoints: 4096
    sample_radius_with_roi: 1.6
    num_sectors: 6
  
  keypoint_weights:
    cls_fc: [256, 256]
    gt_extra_width: [0.2, 0.2, 0.2]
    point_cls_weight: 1.0
  

  augment:
    PointShuffle: True
    ObjectRangeFilter:
      point_cloud_range: [-74.88, -74.88, -2, 74.88, 74.88, 4]
    ObjectSample:
      min_points_dict:
        VEHICLE: 5
        PEDESTRIAN: 10
        CYCLIST: 10
      sample_dict:
        VEHICLE: 15
        PEDESTRIAN: 10
        CYCLIST: 10


pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 2
  val_batch_size: 2
  test_batch_size: 2
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.01
    betas: [0.95, 0.99]
    weight_decay: 0.001

  # evaluation properties
  overlaps: [0.5, 0.5, 0.5]
  difficulties: [0, 1, 2]
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
