dataset:
  name: Waymo
  dataset_path: # /export/share/Datasets/Waymo_1.3/waymo_preprocessed/  # path/to/your/dataset
  cache_dir: ./logs/cache
  # steps_per_epoch_train: 4000

model:
  name: PVRCNNPlusPlus
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"

  point_cloud_range: [-74.88, -74.88, -2, 74.88, 74.88, 4]
  classes: ['VEHICLE', 'PEDESTRIAN', 'CYCLIST']

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 5
    voxel_size: &vsize
      [0.1, 0.1, 0.15]
    max_voxels: [150000, 150000]

  voxel_encoder:
    in_channels: 4
    # feat_channels: [64]
    voxel_size: *vsize
  
  backbone_2d:
    layer_nums: [5, 5]
    layer_strides: [1, 2]
    num_filters: [128, 256]
    upsample_strides: [1, 2]
    num_upsample_filters: [256, 256]

  rpn_module:
    shared_conv_channels: 64
    num_head_conv: 2
    class_names: [ 'Vehicle', 'Pedestrian', 'Cyclist' ]
    voxel_size: *vsize
    feature_map_stride: 8
    nms_pre: 4096
    score_thr: 0.1
    post_center_limit_range: [ -75.2, -75.2, -2, 75.2, 75.2, 4 ]
    num_max_objs: 500
    gaussian_overlap: 0.1
    min_radius: 2
    cls_weight: 1.0
    loc_weight: 2.0
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  roi_grid_pool:
    rcnn_cls_weight: 1.0
    rcnn_reg_weight: 1.0
    rcnn_corner_weight: 1.0
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    code_size: 7
    num_class: 1
    SHARED_FC: [256, 256]
    CLS_FC: [256, 256]
    REG_FC: [256, 256]
    DP_RATIO: 0.3
    TARGET_CONFIG:
      BOX_CODER: ResidualCoder
      ROI_PER_IMAGE: 128
      FG_RATIO: 0.5
      SAMPLE_ROI_BY_EACH_CLASS: True
      CLS_SCORE_TYPE: roi_iou
      CLS_FG_THRESH: 0.75
      CLS_BG_THRESH: 0.25
      CLS_BG_THRESH_LO: 0.1
      HARD_BG_RATIO: 0.8
      REG_FG_THRESH: 0.5
    ROI_GRID_POOL:
      GRID_SIZE: 6
      NAME: VectorPoolAggregationModuleMSG
      NUM_GROUPS: 2
      LOCAL_AGGREGATION_TYPE: voxel_random_choice
      NUM_REDUCED_CHANNELS: 30
      NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
      MSG_POST_MLPS: [ 128 ]
      GROUP_CFG_0:
        NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
        MAX_NEIGHBOR_DISTANCE: 0.8
        NEIGHBOR_NSAMPLE: 32
        POST_MLPS: [ 64, 64 ]
      GROUP_CFG_1:
        NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
        MAX_NEIGHBOR_DISTANCE: 1.6
        NEIGHBOR_NSAMPLE: 32
        POST_MLPS: [ 64, 64 ]


  voxel_set_abstraction:
    voxel_size: *vsize
    num_bev_features: 512
    num_raw_features: 5
    num_keypoints: 4096
    sample_radius_with_roi: 1.6
    num_sectors: 6
    NUM_OUTPUT_FEATURES: 90
    SA_LAYER:
      raw_points:
        NAME: VectorPoolAggregationModuleMSG
        NUM_GROUPS: 2
        LOCAL_AGGREGATION_TYPE: local_interpolation
        NUM_REDUCED_CHANNELS: 1 #2
        NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
        MSG_POST_MLPS: [ 32 ]
        FILTER_NEIGHBOR_WITH_ROI: True
        RADIUS_OF_NEIGHBOR_WITH_ROI: 2.4

        GROUP_CFG_0:
          NUM_LOCAL_VOXEL: [ 2, 2, 2 ]
          MAX_NEIGHBOR_DISTANCE: 0.2
          NEIGHBOR_NSAMPLE: -1
          POST_MLPS: [ 32, 32 ]
        GROUP_CFG_1:
          NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
          MAX_NEIGHBOR_DISTANCE: 0.4
          NEIGHBOR_NSAMPLE: -1
          POST_MLPS: [ 32, 32 ]

      x_conv3:
        DOWNSAMPLE_FACTOR: 4
        INPUT_CHANNELS: 64

        NAME: VectorPoolAggregationModuleMSG
        NUM_GROUPS: 2
        LOCAL_AGGREGATION_TYPE: local_interpolation
        NUM_REDUCED_CHANNELS: 32
        NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
        MSG_POST_MLPS: [128]
        FILTER_NEIGHBOR_WITH_ROI: True
        RADIUS_OF_NEIGHBOR_WITH_ROI: 4.0

        GROUP_CFG_0:
          NUM_LOCAL_VOXEL: [3, 3, 3]
          MAX_NEIGHBOR_DISTANCE: 1.2
          NEIGHBOR_NSAMPLE: -1
          POST_MLPS: [64, 64]
        GROUP_CFG_1:
          NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
          MAX_NEIGHBOR_DISTANCE: 2.4
          NEIGHBOR_NSAMPLE: -1
          POST_MLPS: [ 64, 64 ]

      x_conv4:
        DOWNSAMPLE_FACTOR: 8
        INPUT_CHANNELS: 64

        NAME: VectorPoolAggregationModuleMSG
        NUM_GROUPS: 2
        LOCAL_AGGREGATION_TYPE: local_interpolation
        NUM_REDUCED_CHANNELS: 32
        NUM_CHANNELS_OF_LOCAL_AGGREGATION: 32
        MSG_POST_MLPS: [ 128 ]
        FILTER_NEIGHBOR_WITH_ROI: True
        RADIUS_OF_NEIGHBOR_WITH_ROI: 6.4

        GROUP_CFG_0:
          NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
          MAX_NEIGHBOR_DISTANCE: 2.4
          NEIGHBOR_NSAMPLE: -1
          POST_MLPS: [ 64, 64 ]
        GROUP_CFG_1:
          NUM_LOCAL_VOXEL: [ 3, 3, 3 ]
          MAX_NEIGHBOR_DISTANCE: 4.8
          NEIGHBOR_NSAMPLE: -1
          POST_MLPS: [ 64, 64 ]

  
  keypoint_weights:
    cls_fc: [256, 256]
    gt_extra_width: [0.2, 0.2, 0.2]
    point_cls_weight: 1.0
  

  augment:
    PointShuffle: True
    ObjectRangeFilter:
      point_cloud_range: [-74.88, -74.88, -2, 74.88, 74.88, 4]
    ObjectSample:
      min_points_dict:
        VEHICLE: 5
        PEDESTRIAN: 10
        CYCLIST: 10
      sample_dict:
        VEHICLE: 15
        PEDESTRIAN: 10
        CYCLIST: 10


pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 2
  val_batch_size: 2
  test_batch_size: 2
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.01
    betas: [0.95, 0.99]
    weight_decay: 0.001

  # evaluation properties
  overlaps: [0.5, 0.5, 0.5]
  difficulties: [0, 1, 2]
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
